remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme
exclude: [README.md]
github:
  repository_name: Guanaco
  repository_url: https://github.com/bhaaksema/guanaco
  website_url: https://bhaaksema.github.io/guanaco
  zip_url: https://github.com/bhaaksema/guanaco/zipball/main
  contrib1_name: mborchers
  contrib1_url: https://github.com/Maulol13
  contrib2_name: bhaaksema
  contrib2_url: https://github.com/bhaaksema
  contrib3_name: lsibma
  contrib3_url: https://github.com/lisannesibma
