remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme
exclude: [README.md]
github:
  repository_name: Guanaco
  project_tagline: "A Syntactic Proof Guide for Epistemic Logic"
  repository_url: https://github.com/bhaaksema/guanaco
  zip_url: https://github.com/bhaaksema/guanaco/zipball/main
