remote_theme: pages-themes/cayman@v0.2.0
show_downloads: true
plugins:
  - jekyll-remote-theme
exclude: [README.md]
github:
  repository_name: Guanaco
  repository_url: https://github.com/bhaaksema/guanaco
  website_url: https://bhaaksema.github.io/guanaco
  zip_url: https://github.com/bhaaksema/guanaco/zipball/main
contributor:
  1_name: mborchers
  1_url: https://github.com/Maulol13
  2_name: bhaaksema
  2_url: https://github.com/bhaaksema
  3_name: lsibma
  3_url: https://github.com/lisannesibma
