title: Logical Aspects of Multi-agent Systems
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
show_downloads: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme